In [1]:
import pandas as pd
df=pd.read_csv("selfmade.csv")
df

,Title,Tag,genres,rating
0,interstellar,3.0,"['Animation', 'Comedy', 'Family']",3.0
1,inception,1.0,"['Adventure', 'Fantasy', 'Family']",4.5
2,darkknight,3.0,"['Romance', 'Comedy']",2.5
3,NaN,NaN,"['Comedy', 'Drama', 'Romance']",NaN
4,NaN,NaN,['Comedy'],NaN
5,NaN,NaN,"['Action', 'Crime', 'Drama', 'Thriller']",NaN
6,NaN,NaN,"['Comedy', 'Romance']",NaN
7,NaN,NaN,"['Action', 'Adventure', 'Drama', 'Family']",NaN
8,NaN,NaN,"['Action', 'Adventure', 'Thriller']",NaN
9,NaN,NaN,"['Adventure', 'Action', 'Thriller']",NaN
10,NaN,NaN,"['Comedy', 'Drama', 'Romance']",NaN
11,NaN,NaN,"['Comedy', 'Horror']",NaN
12,NaN,NaN,"['Family', 'Animation', 'Adventure']",NaN
13,NaN,NaN,"['History', 'Drama']",NaN
14,NaN,NaN,"['Action', 'Adventure']",NaN
15,NaN,NaN,"['Drama', 'Crime']",NaN
16,NaN,NaN,"['Drama', 'Romance']",NaN
17,NaN,NaN,"['Crime', 'Comedy']",NaN
18,NaN,NaN,"['Crime', 'Comedy', 'Adventure']",NaN
19,NaN,NaN,"['Action', 'Comedy', 'Crime']",NaN
20,NaN,NaN,"['Comedy', 'Thriller', 'Crime']",NaN
21,NaN,NaN,"['Drama', 'Thriller']",NaN
22,NaN,NaN,"['Action', 'Adventure', 'Crime', 'Thriller']",NaN
23,NaN,NaN,"['Drama', 'Fantasy', 'Science Fiction', 'Thril...",NaN
24,NaN,NaN,"['Drama', 'Romance']",NaN
25,NaN,NaN,['Drama'],NaN
26,NaN,NaN,"['Comedy', 'Drama', 'Family']",NaN
27,NaN,NaN,"['Drama', 'Romance']",NaN
28,NaN,NaN,"['Fantasy', 'Science Fiction', 'Adventure']",NaN
29,NaN,NaN,"['Drama', 'Crime']",NaN
30,NaN,NaN,"['Drama', 'Crime']",NaN
31,NaN,NaN,"['Science Fiction', 'Thriller', 'Mystery']",NaN
32,NaN,NaN,"['Fantasy', 'Drama', 'Comedy', 'Family']",NaN
33,NaN,NaN,"['History', 'Drama', 'Romance']",NaN
34,NaN,NaN,['Drama'],NaN
35,NaN,NaN,"['Adventure', 'History', 'Drama', 'Family']",NaN
36,NaN,NaN,"['Comedy', 'Family', 'Romance']",NaN
37,NaN,NaN,"['Comedy', 'Drama', 'Romance']",NaN
38,NaN,NaN,['Drama'],NaN
39,NaN,NaN,"['Drama', 'War']",NaN
40,NaN,NaN,"['Action', 'Crime', 'Drama', 'History']",NaN
41,NaN,NaN,"['Drama', 'Romance']",NaN
42,NaN,NaN,"['Action', 'Fantasy']",NaN
43,NaN,NaN,"['Fantasy', 'Drama', 'Comedy', 'Thriller']",NaN

In [3]:
df['genres']=df['genres'].sorted()

AttributeError: 'Series' object has no attribute 'sorted'

In [1]:
import csv
with open('final.csv',utf=) as csv_file:
    csv_reader=csv.reader(csv_file,delimiter=",")
    for row in csv_reader:
        print(row)

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5232: character maps to <undefined>

In [43]:
import csv
import re
with open('selfmade.csv') as csv_file:
    csv_reader=csv.reader(csv_file,delimiter=",")
    for row in csv_reader:
        listofgenres=[]
        match = re.findall(r'\'([^\']*)\'', row[2])
        print(match)
       # for item in match:
        #    listofgenres.append(item)
         #   print(listofgenres)

[]
['Animation', 'Comedy', 'Family']
['Adventure', 'Fantasy', 'Family']
['Romance', 'Comedy']
['Comedy', 'Drama', 'Romance']
['Comedy']
['Action', 'Crime', 'Drama', 'Thriller']
['Comedy', 'Romance']
['Action', 'Adventure', 'Drama', 'Family']
['Action', 'Adventure', 'Thriller']
['Adventure', 'Action', 'Thriller']
['Comedy', 'Drama', 'Romance']
['Comedy', 'Horror']
['Family', 'Animation', 'Adventure']
['History', 'Drama']
['Action', 'Adventure']
['Drama', 'Crime']
['Drama', 'Romance']
['Crime', 'Comedy']
['Crime', 'Comedy', 'Adventure']
['Action', 'Comedy', 'Crime']
['Comedy', 'Thriller', 'Crime']
['Drama', 'Thriller']
['Action', 'Adventure', 'Crime', 'Thriller']
['Drama', 'Fantasy', 'Science Fiction', 'Thriller']
['Drama', 'Romance']
['Drama']
['Comedy', 'Drama', 'Family']
['Drama', 'Romance']
['Fantasy', 'Science Fiction', 'Adventure']
['Drama', 'Crime']
['Drama', 'Crime']
['Science Fiction', 'Thriller', 'Mystery']
['Fantasy', 'Drama', 'Comedy', 'Family']
['History', 'Drama', 'Romance']
['Drama']
['Adventure', 'History', 'Drama', 'Family']
['Comedy', 'Family', 'Romance']
['Comedy', 'Drama', 'Romance']
['Drama']
['Drama', 'War']
['Action', 'Crime', 'Drama', 'History']
['Drama', 'Romance']
['Action', 'Fantasy']
['Fantasy', 'Drama', 'Comedy', 'Thriller']

In [19]:
import csv
import re
x=set()
with open('selfmade.csv') as csv_file:
    csv_reader=csv.reader(csv_file,delimiter=",")
    for row in csv_reader:
        listofgenres=[]
        match = re.findall(r'\'([^\']*)\'', row[2])
        for item in match:
            x.add(item)
print(x)
for item in x:
    listofgenres.append(item)
print(listofgenres)
listofgenres.sort()
print(listofgenres)

{'Animation', 'Action', 'War', 'Science Fiction', 'Mystery', 'Romance', 'Adventure', 'History', 'Family', 'Drama', 'Fantasy', 'Thriller', 'Crime', 'Comedy', 'Horror'}
['Animation', 'Action', 'War', 'Science Fiction', 'Mystery', 'Romance', 'Adventure', 'History', 'Family', 'Drama', 'Fantasy', 'Thriller', 'Crime', 'Comedy', 'Horror']
['Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Mystery', 'Romance', 'Science Fiction', 'Thriller', 'War']

In [27]:
import csv
import re
finalbinary=[]
with open('selfmade.csv') as csv_file:
    csv_reader=csv.reader(csv_file,delimiter=",")
    for row in csv_reader:
        genresbinary=[]
        for standardgenres in listofgenres:
            if standardgenres in row[2]:
                genresbinary.append(1)
            else:
                genresbinary.append(0)
            
        finalbinary.append(genresbinary)
print(finalbinary)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], [0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0], [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0], [0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0]]

In [40]:
import pandas as pd
df=pd.read_csv('selfmade.csv')
row,column=df.shape
for i in range(row):
    df['genres'][i]=finalbinary[i]#$,error='coerce'

c:\users\attaullah bhatti\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [41]:
df['genres']

0     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
1     [0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
2     [0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]
3     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
4     [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0]
5     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
6     [1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0]
7     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
8     [1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
9     [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
10    [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
11    [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0]
12    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
13    [0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
14    [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0]
15    [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
16    [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
17    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0]
18    [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
19    [0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
20    [1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
21    [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
22    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0]
23    [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
24    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0]
25    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0]
26    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
27    [0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
28    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0]
29    [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0]
30    [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
31    [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
32    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0]
33    [0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
34    [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0]
35    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
36    [0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0]
37    [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]
38    [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0]
39    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
40    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1]
41    [1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0]
42    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0]
43    [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
Name: genres, dtype: object